### ISSUE TITLE
cci an die leine legen

### ISSUE THREAD

**Issue by gixxerPS** [gixxerPS/myHomeCAN-cci#7]
watchdog aktivieren.
Problem des "Einfrierens" eingegrenzt. Tritt an nur an PU's mit induktiven Lasten (Rollos) auf.
Das cci schickt nach Einfrieren noch zyklisch das Prozessabbild, aber kein Alive mehr und reagiert auch nicht auf eingehende Botschaften (Ausgänge schalten).
Scheint ein EMV Hardware Problem zu sein.
Vorschlag für Umgehung: Watchdog löst nach z.B. 300ms aus wenn TIMER1_OVF_vect QuarterSecondCounter_u8 nicht geändert hat.

**Comment by gixxerPS** [comment]
WDTCR – Watchdog Timer Control Register
besitzt Prescaler Bits WDP0, WDP1, WDP2.
Mit WDP0 und WDP2 = true wäre der Timeout bei ca. 0,52s.
Das würde gut zum Takt von TIMER1_OVF_vect passen.
Oder man nimmt noch einen größeren Prescaler mit Timeout von ca. 1s (WDP1 und WDP2 = true). 
Dann hätte man noch einen TIMER1_OVF_vect Takt Reserve.

**Comment by MemberM** [comment]
Mit einem halben Jahr Verspätung wird Issue nun im Mittagsschlaf von Paul erledigt ;-)
